# Generated by Django 5.1.3 on 2025-01-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrapayments',
            name='extra_service_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extrapayments',
            name='extra_service_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extrapayments',
            name='extra_service_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentcosts',
            name='rentable_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentcosts',
            name='rentable_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentcosts',
            name='rentable_es',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
