# Generated by Django 5.1.3 on 2025-02-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_extrapayments_extra_service_de_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtraPayments',
            new_name='ExtraPayment',
        ),
    ]
