# Generated by Django 5.1.3 on 2025-02-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_rename_extrapayments_extrapayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayments',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=10, unique=True),
        ),
    ]
