# Generated by Django 5.1.3 on 2025-02-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_alter_monthlypayments_payment_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyPayments',
            new_name='MonthlyPayment',
        ),
    ]
