# Generated by Django 5.1.3 on 2025-02-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_rename_monthlypayments_monthlypayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentCosts',
            new_name='RentCost',
        ),
    ]
