# Generated by Django 5.1.3 on 2025-01-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=3000)),
                ('whatsapp_number', models.CharField(max_length=15)),
            ],
        ),
    ]
