# Generated by Django 5.1.3 on 2025-01-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainer',
            name='potrait',
            field=models.ImageField(default='static/images/staff/personal_trainers/default.jpg', upload_to='static/images/staff/personal_trainers'),
        ),
    ]
