# Generated by Django 5.1.3 on 2025-01-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_personaltrainer_potrait'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaltrainer',
            old_name='potrait',
            new_name='portrait',
        ),
    ]
