# Generated by Django 5.1.3 on 2025-01-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_potrait_personaltrainer_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltrainer',
            name='whatsapp_number',
            field=models.CharField(max_length=20),
        ),
    ]
