# Generated by Django 5.1.3 on 2025-01-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_personaltrainer_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('portrait', models.ImageField(default='static/images/staff/personal_trainers/default.jpg', upload_to='static/images/staff/personal_trainers')),
                ('role', models.CharField(max_length=300)),
            ],
        ),
    ]
