# Generated by Django 5.1.3 on 2025-01-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainer',
            name='languages_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='languages_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='languages_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='text_de',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='text_en',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='text_es',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='role_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='role_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='role_es',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
