# Generated by Django 5.1.3 on 2025-02-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_personaltrainer_languages_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltrainer',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personaltrainer',
            name='text_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personaltrainer',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personaltrainer',
            name='text_es',
            field=models.TextField(null=True),
        ),
    ]
