# Generated by Django 5.1.3 on 2025-01-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_personaltrainers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanningBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/images/services/gym_equipment')),
                ('description', models.CharField(max_length=1001)),
            ],
        ),
    ]
