# Generated by Django 5.1.3 on 2025-01-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_tanningbed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanningbed',
            name='image',
            field=models.ImageField(upload_to='static/images/services/tanning_bed'),
        ),
    ]
