# Generated by Django 5.1.3 on 2025-01-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_tanningbed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymequipment',
            name='description_de',
            field=models.CharField(max_length=1001, null=True),
        ),
        migrations.AddField(
            model_name='gymequipment',
            name='description_en',
            field=models.CharField(max_length=1001, null=True),
        ),
        migrations.AddField(
            model_name='gymequipment',
            name='description_es',
            field=models.CharField(max_length=1001, null=True),
        ),
        migrations.AddField(
            model_name='gymequipment',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gymequipment',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gymequipment',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainers',
            name='description_de',
            field=models.CharField(max_length=1001, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainers',
            name='description_en',
            field=models.CharField(max_length=1001, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainers',
            name='description_es',
            field=models.CharField(max_length=1001, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainers',
            name='type_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainers',
            name='type_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainers',
            name='type_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tanningbed',
            name='description_de',
            field=models.CharField(max_length=1001, null=True),
        ),
        migrations.AddField(
            model_name='tanningbed',
            name='description_en',
            field=models.CharField(max_length=1001, null=True),
        ),
        migrations.AddField(
            model_name='tanningbed',
            name='description_es',
            field=models.CharField(max_length=1001, null=True),
        ),
        migrations.AddField(
            model_name='tanningbed',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tanningbed',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tanningbed',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
