# Generated by Django 5.1.3 on 2025-02-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_gymequipment_description_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymequipment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gymequipment',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gymequipment',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gymequipment',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personaltrainers',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personaltrainers',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personaltrainers',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='personaltrainers',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tanningbed',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tanningbed',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tanningbed',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tanningbed',
            name='description_es',
            field=models.TextField(null=True),
        ),
    ]
