# Generated by Django 5.1.3 on 2025-01-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonaltimetable',
            name='season',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter')], max_length=100),
        ),
    ]
