# Generated by Django 5.1.3 on 2025-01-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_seasonaltimetable_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonaltimetable',
            name='dates_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seasonaltimetable',
            name='dates_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seasonaltimetable',
            name='dates_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='summertimetable',
            name='days_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='summertimetable',
            name='days_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='summertimetable',
            name='days_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wintertimetable',
            name='days_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wintertimetable',
            name='days_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wintertimetable',
            name='days_es',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
