# Generated by Django 5.1.3 on 2025-02-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_seasonaltimetable_dates_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonaltimetable',
            name='season',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter')], max_length=100, unique=True),
        ),
    ]
